"use client";

import { useEffect, useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type RecordItem = { id: string; date: string; recommended_session: string; readiness_bucket: string; rule_version: string; next_day_recovery: number | null; false_green_signal: boolean; false_red_signal: boolean; outcome: Record<string, unknown> | null };
const sessions = ["off", "recovery", "zone2", "tempo", "high_intensity", "strength_only"];

export function OutcomeReview() {
  const [records, setRecords] = useState<RecordItem[]>([]); const [summary, setSummary] = useState<Record<string, number>>({});
  const [selectedId, setSelectedId] = useState(""); const [form, setForm] = useState<Record<string, unknown>>({ completed_session: true, chosen_session: "zone2", session_rpe: 5, appropriateness_rating: 3 });
  const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const selected = useMemo(() => records.find((record) => record.id === selectedId) ?? records[0], [records, selectedId]);
  const load = async () => { const res = await fetch("/api/outcomes"); const data = await res.json(); if (res.ok) { setRecords(data.records ?? []); setSummary(data.summary ?? {}); } else setMessage(data.error ?? "Unable to load outcome data. Run migration 010 first."); };
  useEffect(() => { load().catch(() => setMessage("Unable to load outcome data.")); }, []);
  useEffect(() => { if (selected) { setSelectedId(selected.id); setForm({ completed_session: selected.outcome?.completed_session ?? true, chosen_session: selected.outcome?.chosen_session ?? selected.recommended_session, session_rpe: selected.outcome?.session_rpe ?? 5, achieved_intended_intensity: selected.outcome?.achieved_intended_intensity ?? true, excessive_fatigue: selected.outcome?.excessive_fatigue ?? false, illness_or_pain: selected.outcome?.illness_or_pain ?? false, appropriateness_rating: selected.outcome?.appropriateness_rating ?? 3, notes: selected.outcome?.notes ?? "" }); } }, [selected?.id]);
  const set = (key: string, value: unknown) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!selected) return; setSaving(true); setMessage(null); const res = await fetch("/api/outcomes", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, recommendation_id: selected.id, date: selected.date }) }); setSaving(false); setMessage(res.ok ? "Outcome saved. Your next review will include it." : ((await res.json().catch(() => ({}))).error ?? "Could not save outcome.")); if (res.ok) await load(); };
  return <div className="space-y-6">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Recommendations", summary.recommendations], ["Outcomes logged", summary.logged_outcomes], ["False-green signals", summary.false_green_signals], ["False-red signals", summary.false_red_signals]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value ?? 0}</p></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle className="text-base">Log an outcome</CardTitle></CardHeader><CardContent className="space-y-4 text-sm">{!selected ? <p className="text-muted-foreground">No recommendations are available yet. Sync and generate a recommendation first.</p> : <><label className="block">Recommendation<select value={selected.id} onChange={(e) => setSelectedId(e.target.value)} className="mt-1 block w-full rounded border px-3 py-2">{records.map((record) => <option key={record.id} value={record.id}>{record.date} — {record.recommended_session.replaceAll("_", " ")}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label>What did you do?<select value={String(form.chosen_session)} onChange={(e) => set("chosen_session", e.target.value)} className="mt-1 block w-full rounded border px-3 py-2">{sessions.map((session) => <option key={session} value={session}>{session.replaceAll("_", " ")}</option>)}</select></label><label>Session RPE (1–10)<input type="number" min="1" max="10" value={Number(form.session_rpe)} onChange={(e) => set("session_rpe", Number(e.target.value))} className="mt-1 block w-full rounded border px-3 py-2" /></label><label>Was the recommendation appropriate? (1–5)<input type="number" min="1" max="5" value={Number(form.appropriateness_rating)} onChange={(e) => set("appropriateness_rating", Number(e.target.value))} className="mt-1 block w-full rounded border px-3 py-2" /></label><label className="flex items-center gap-2 pt-6"><input type="checkbox" checked={Boolean(form.completed_session)} onChange={(e) => set("completed_session", e.target.checked)} />Completed session</label></div><div className="flex flex-wrap gap-4"><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(form.achieved_intended_intensity)} onChange={(e) => set("achieved_intended_intensity", e.target.checked)} />Achieved intended intensity</label><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(form.excessive_fatigue)} onChange={(e) => set("excessive_fatigue", e.target.checked)} />Excessive fatigue afterward</label><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(form.illness_or_pain)} onChange={(e) => set("illness_or_pain", e.target.checked)} />Illness or pain</label></div><label className="block">Notes<textarea value={String(form.notes ?? "")} onChange={(e) => set("notes", e.target.value)} rows={2} className="mt-1 block w-full rounded border px-3 py-2" placeholder="Optional context: travel, soreness, race, life stress…" /></label><Button type="button" loading={saving} onClick={save}>Save outcome</Button></>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Backtest signals</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p className="text-muted-foreground">These are review prompts—not proof that a recommendation was wrong. They help find patterns across algorithm versions.</p>{records.filter((record) => record.false_green_signal || record.false_red_signal).length === 0 ? <p>No review signals yet.</p> : records.filter((record) => record.false_green_signal || record.false_red_signal).map((record) => <div key={record.id} className="rounded border p-3"><strong>{record.date}</strong> — {record.false_green_signal ? "possible false-green" : "possible false-red"}; recommended {record.recommended_session.replaceAll("_", " ")}; next-day recovery {record.next_day_recovery ?? "not yet available"}.</div>)}</CardContent></Card>
    {message && <p className="text-sm text-muted-foreground">{message}</p>}
  </div>;
}
